AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda with Aurora Data API

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10
    MemorySize: 512

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - http://localhost:5173
          - https://www.mycoins.pl
          - https://<your-amplify>.amplifyapp.com
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowMethods:
          - GET
          - POST
          - OPTIONS

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler

      Environment:
        Variables:
          DB_CLUSTER_ARN: "arn:aws:rds:eu-west-2:603013158700:cluster:database-1"
          DB_SECRET_ARN: "arn:aws:secretsmanager:eu-west-2:603013158700:secret:rds!cluster-fa5790c8-6389-4d2f-973c-b36e81d62670-QLIq17"
          DB_NAME: "appdb"

      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteStatement
                - rds-data:BatchExecuteStatement
                - rds-data:BeginTransaction
                - rds-data:CommitTransaction
                - rds-data:RollbackTransaction
              Resource: "*"
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:eu-west-2:603013158700:secret:rds!cluster-fa5790c8-6389-4d2f-973c-b36e81d62670-QLIq17

      Events:
        ProxyApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY

Outputs:
  HttpApiUrl:
    Description: Base URL for API
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com'
